export type IconName =
    | 'arrow_right'
    | 'arrow-right-top'
    | 'dollar-sign'
    | 'facebook'
    | 'factory'
    | 'house'
    | 'instagram'
    | 'krupomol_logo'
    | 'linkedin'
    | 'mailbox'
    | 'map-pinned'
    | 'phone-call'
    | 'tiktok'
    | 'wheat';
