export type IconName =
	| "arrow-right-top"
	| "dollar-sign"
	| "facebook"
	| "factory"
	| "house"
	| "instagram"
	| "krupomol_logo"
	| "linkedin"
	| "mailbox"
	| "map-pinned"
	| "menu_icon"
	| "phone-call"
	| "tiktok"
	| "wheat"
	| "x-mark"
